### ISSUE TITLE
Table Caption

### ISSUE THREAD

**Issue by Zamdrist** [shps951023/HtmlTableHelper#23]
Are table captions implemented? I didn't see it and may have just missed it. Thanks.

**Comment by shps951023** [comment]
Yes, currently there is no implementation of the table captions, and I am included in the next edition update
Thank you for your

```html
<table>
  <caption>Monthly savings</caption>
  <tr>
    <th>Month</th>
    <th>Savings</th>
  </tr>
  <tr>
    <td>January</td>
    <td>$100</td>
  </tr>
</table>
```

**Comment by shps951023** [comment]
@Zamdrist 

HtmlTableHelper 1.2.1 support caption by builder

![image](https://user-images.githubusercontent.com/12729184/55818555-74085280-5b29-11e9-93b4-43e62cbbc1b3.png)
